[package]
name = "xmz_server"
version = "0.21.0"
authors = ["Stefan Müller <s.mueller@it.kls-glt.de>"]
description = "xMZ-Mod-Touch Server"
documentation = "https://gaswarnanlagen.com/xmz-mod-touch"
homepage = "https://gaswarnanlagen.com/xmz-mod-touch"
repository = "https://github.com/Kliemann-Service-GmbH/xMZ-Mod-Touch-Server.git"
license = "GPL-2.0"

[[bin]]
name = "xmz-server"
path = "src/main.rs"
doc = false

[features]
development = []

[dev-dependencies]
env_logger = "0.3"

[dependencies]
clap = "2.20"
env_logger = "0.3.5"
error-chain = "0.7.2"
gtk = { git = "https://github.com/gtk-rs/gtk.git" }
iron = "0.5.1"
libmodbus-rs = { git = "https://github.com/zzeroo/libmodbus-rs.git" }
log = "0.3.6"
nom = "2.0.1"
rand="0.3"
router = "*"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
sysfs_gpio = "0.4"
