[package]
name = "xmz_server"
version = "0.20.1"
authors = ["Stefan Müller <s.mueller@it.kls-glt.de>"]
description = "xMZ-Mod-Touch Server"
documentation = "https://gaswarnanlagen.com/xmz-mod-touch"
homepage = "https://gaswarnanlagen.com/xmz-mod-touch"
repository = "https://github.com/Kliemann-Service-GmbH/xMZ-Mod-Touch-Server.git"
license = "GPL-2.0"

[dev-dependencies]
env_logger = "0.3"

[dependencies]
error-chain = "^0.7.1"
libmodbus-rs = { git = "https://github.com/zzeroo/libmodbus-rs.git" }
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
