# FIXME: Umbenennen nach 'xmz_mod_touch_server'
[package]
name = "xmz_server"
version = "0.30.0"
authors = ["Stefan Müller <s.mueller@it.kls-glt.de>"]
description = "xMZ-Mod-Touch Server"
documentation = "https://gaswarnanlagen.com/xmz-mod-touch"
homepage = "https://gaswarnanlagen.com/xmz-mod-touch"
repository = "https://github.com/Kliemann-Service-GmbH/xMZ-Mod-Touch-Server.git"
license = "GPL-2.0"

[[bin]]
name = "xmz-server"
path = "src/main.rs"
# doc = false

[features]
development = []

[dependencies]
libmodbus-rs = { git = "https://github.com/zzeroo/libmodbus-rs.git" }
sysfs_gpio = "*"
log = "*"
env_logger = "*"
