[package]
name = "xmz_server"
version = "0.13.0"
authors = ["Stefan Müller <s.mueller@it.kls-glt.de>"]
description = "xMZ-Mod-Touch Server Library and Binaries"
documentation = "https://gaswarnanlagen.com/xmz-mod-touch"
homepage = "https://gaswarnanlagen.com/xmz-mod-touch"
repository = "https://github.com/Kliemann-Service-GmbH/xMZ-Mod-Touch-Server.git"
license = "GPL-2.0"

[[bin]]
name = "xmz-server-bin"
path = "src/xmz-server-bin.rs"

[dependencies]
libmodbus-rs = { git = "https://github.com/zzeroo/libmodbus-rs.git" }
nanomsg = { git = "https://github.com/thehydroimpulse/nanomsg.rs.git" }
rustc-serialize = "0.3"
sysfs_gpio = "*"
